
name: Release

on:
  push:
    branches: [ "master" ]
    tags:
      - v*
env:
  REGISTRY_NAME: fonsecabarreto
  IMAGE_NAME: gpicm-map-interpolation-app

jobs:
  pushToDockerHub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: docker build  -f ./monitoring-map/Dockerfile --target production --tag $REGISTRY_NAME/$IMAGE_NAME ./

    - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
    - run: docker push $REGISTRY_NAME/$IMAGE_NAME:latest

    - name: Clean up
      run: rm -f .env

